# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://vakameghana:Vakameghana@cluster0.oxfidxn.mongodb.net/foodshare

# Server Configuration
server.port=8080

# Optional: Logging
logging.level.org.springframework.data.mongodb=DEBUG